### ISSUE TITLE
USD is missing

### ISSUE THREAD

**Issue by tbm** [LucaFilipozzi/spi-reimbursement-request#1]
USD (American dollar) got removed in commit fe5d2cdd2585.

I don't know how flexible your code is.  *Ideally*, people would be able to choose from 2 options from a menu and depending on those options *different* fields would show up.

Actually, we probably need 3 options since USD transfers can be outside the US as well.

* Bank transfer within US (ACH direct deposit)
* Bank transfer outside the US (wire transfer)
* Check (delivered by post)

For ACH, we need:

* ABA number (routing number)
* Bank account

For check we need:

* Street 1
* Street 2 (optional)
* City
* Zip code (post code)
* State (optional)
* Country (optional)

I'm not sure what we need for international wire.  At least:

* Account number
* Routing number
* Bank name

probably also bank address, but we can clarify and add that later

I think payment via Zelle (you give an email, they do ACH on the backend) should be possible too but I'll check with Michael first. I don't think we've done that.

**Comment by LucaFilipozzi** [comment]
USD is in progress.

**Comment by LucaFilipozzi** [comment]
USD has been added.
