### ISSUE TITLE
Do we need date?

### ISSUE THREAD

**Issue by tbm** [LucaFilipozzi/spi-reimbursement-request#10]
I wonder if we actually need "Date" as something the user can select. Shouldn't that always be the current date anyway? (And we only need it to embed in the filename. I don't think it needs to be in the PDF itself).

**Comment by LucaFilipozzi** [comment]
If this is a form that is used to provide banking information, then maybe it needs neither date nor amount nor project. You generate it once, keep it on hand, and provide it every time you make a reimbursement request. Or maybe you generate / submit it once, and only regenerate / resubmit it again if the information changes.

OR

If this is a form that should be submitted with each reimbursement request, then it needs Project, Date of Submission, Event Name, Event Date, etc. etc.

Right now, it's somewhere in between.

**Comment by LucaFilipozzi** [comment]
Once you decide on whether to have a date on this form, then we can consider modifying the filename to include date.

**Comment by tbm** [comment]
As per issue #12 the form is going to be specific for each reimbursement (since we want to have the amount).
