### ISSUE TITLE
Sync list with TransferWise

### ISSUE THREAD

**Issue by tbm** [LucaFilipozzi/spi-reimbursement-request#4]
TransferWise [supports some new currencies](https://transferwise.com/help/11/getting-started/2571907/what-currencies-do-you-support).

The script needs to add:

* KRW — South Korean won
* TZS — Tanzanian shillings
* UGX — Ugandan shillings

I will send a patch.

**Comment by LucaFilipozzi** [comment]
code structure has changed; please pull latest
